### ISSUE TITLE
'download' fetches last revision, not current state

### ISSUE THREAD

**Issue by DougInAMug** [hedgedoc/cli#39]
A collective I'm part of use CodiMD for meeting minutes. I was using a script to transfer the pad to our website using `curl URL/download`. As far as I know, this used to capture the current state of the pad, but recently (perhaps an admin updated the [instance](https://codi.kanthaus.online/)?) it captures the last revision. This is unfortunate, since there is no way for a user to generate a revision, meaning they must sit patiently if they wish to use the API, or just do it manually.

Thanks in advance!

**Comment by hugopeixoto** [comment]
Hi @DougInAMug, it seems like you're using the Hedgedoc API on your own scripts. This repository is focused on the cli tool.

I'd recommend opening up an issue on https://github.com/hedgedoc/hedgedoc instead, if the API changed. I don't see what could have changed to trigger that behavior though.

I'm closing this issue, but feel free to comment if you think we should address something here.

**Comment by DougInAMug** [comment]
Thanks @hugopeixoto

I'll go there if I encounter the issue again, I can't repeat it anymore anyway :)
