### ISSUE TITLE
How to authenticate CLI if using an auth provider?

### ISSUE THREAD

**Issue by nsheff** [hedgedoc/cli#44]
When I created my hedgedoc account at the demo server, I used GitHub to authenticate.

Now I'd like to use the CLI, but both the `--email` and `--ldap` options require a username and password. As far as I know, I never set up a specific password for hedgedoc because authentication is happening via GitHub.

So, I'm confused at how I can use this CLI when my user account lacks a password.

**Comment by pirate** [comment]
I don't believe there's any mechanism to log in with Github on the CLU right now. It may be tricky to build without some sort of API token generation infrastructure on the server side to issue auth keys for CLI use, which will require non-neglible effort to build.

**Comment by ErikMichelson** [comment]
As @pirate already indicated, with HedgeDoc 1.x this is not possible.

HedgeDoc 2.0 however will have the concept of API tokens which will be used instead, no matter which auth provider was used.

**Comment by bbigras** [comment]
Would it be possible to login using a browser and export the cookie file with something like https://github.com/lennonhill/cookies-txt ?

**Comment by ErikMichelson** [comment]
Yes, this should work. You can try to set the environment variable `HEDGEDOC_COOKIES_FILE` to your cookie file.

**Comment by hugopeixoto** [comment]
With the `HEDGEDOC_COOKIES_FILE` option, I think we can close this. Let us know if this didn't work or if you need some help setting it up.

**Comment by mindfuucker** [comment]
Hi, I'm struggling with authentication. I'm using a self-hosted OIDC/OAuth2 provider called Authentik to login into HedgeDoc. This works great with just the press of a button. 

What I've done/tried:
1. Extract the cookie, isolated connect.sid line
2. Changed docs.domain.com to http://127.0.0.1:3000 in the key.conf
3. All defaults apply to me, so no setting of env settings. 

![image](https://user-images.githubusercontent.com/5075692/174491503-c315be34-e1ea-434e-b706-c58c7077f0b8.png)
